name: Big Tuna Digital
favicon: null
layout_spectrum: 0.21760877268388867
typography_spectrum: 0.6515670367516577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.786773090949282
  lightness: 0.4336231639608741
  saturation: 0.18688503955490887
  rhythmicContrast: 0.46454041730612516
purpose: []
